<?php

namespace Proxies\__CG__\webStudent\EtudiantBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Promo extends \webStudent\EtudiantBundle\Entity\Promo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setAnnee($annee)
    {
        $this->__load();
        return parent::setAnnee($annee);
    }

    public function getAnnee()
    {
        $this->__load();
        return parent::getAnnee();
    }

    public function setEtudiant(\webStudent\EtudiantBundle\Entity\Etudiant $etudiant)
    {
        $this->__load();
        return parent::setEtudiant($etudiant);
    }

    public function getEtudiant()
    {
        $this->__load();
        return parent::getEtudiant();
    }

    public function addEtudiant(\webStudent\EtudiantBundle\Entity\Etudiant $etudiants)
    {
        $this->__load();
        return parent::addEtudiant($etudiants);
    }

    public function removeEtudiant(\webStudent\EtudiantBundle\Entity\Etudiant $etudiants)
    {
        $this->__load();
        return parent::removeEtudiant($etudiants);
    }

    public function getEtudiants()
    {
        $this->__load();
        return parent::getEtudiants();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'annee', 'etudiants');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}