<?php

namespace Proxies\__CG__\webStudent\EtudiantBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Section extends \webStudent\EtudiantBundle\Entity\Section implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setUtilisateur(\webStudent\EtudiantBundle\Entity\Utilisateur $utilisateur)
    {
        $this->__load();
        return parent::setUtilisateur($utilisateur);
    }

    public function getUtilisateur()
    {
        $this->__load();
        return parent::getUtilisateur();
    }

    public function addUtilisateur(\webStudent\EtudiantBundle\Entity\Utilisateur $utilisateurs)
    {
        $this->__load();
        return parent::addUtilisateur($utilisateurs);
    }

    public function removeUtilisateur(\webStudent\EtudiantBundle\Entity\Utilisateur $utilisateurs)
    {
        $this->__load();
        return parent::removeUtilisateur($utilisateurs);
    }

    public function getUtilisateurs()
    {
        $this->__load();
        return parent::getUtilisateurs();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'code', 'nom', 'utilisateurs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}