<?php

namespace webStudent\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodeStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodeStageRepository extends EntityRepository
{

	public function findPeriodesAVenir()
	{
		$pAnneeEnCours = date('Y-m-d');
		/*$queryBuilder = $this->_em->createQueryBuilder()
                              ->select('p')
							  ->where('p.dateDebut > :dateAnneeEnCours')
								->setParameter('dateAnneeEnCours', $pAnneeEnCours)
								->orderBy('p.dateDebut', 'ASC')
                              ->from($this->_entityName, 'p');*/
		 // Dans un repository, $this->_entityName est le namespace de l'entité gérée
		// Ici, il vaut donc webStudent\EtudiantBundle\Entity\PeriodeStage

		$queryBuilder = $this->createQueryBuilder('p')
								->where('p.dateDebut > :dateAnneeEnCours')
								->setParameter('dateAnneeEnCours', $pAnneeEnCours)
								->orderBy('p.dateDebut', 'ASC');
                              
							  
     
 
    // On a fini de construire notre requête
 
    // On récupère la Query à partir du QueryBuilder
    $query = $queryBuilder->getQuery();
 
    // On récupère les résultats à partir de la Query
    $resultats = $query->getResult();
 
    // On retourne ces résultats
    return $resultats;
}



}
