<?php

namespace webStudent\EtudiantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends EntityRepository
{
public function getPromoAvecEtudiants()
	{
  $qb = $this->createQueryBuilder('p')
             ->leftJoin('p.etudiants', 'e')
             ->addSelect('e');
 
  return $qb->getQuery()
            ->getResult();
	}

}
