parameters:
#    web_student_etudiant.example.class: webStudent\EtudiantBundle\Example

services:
#    web_student_etudiant.example:
#        class: %web_student_etudiant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
